version: "3"

services:
  app:
    image: paperless-nextcloud-sync
    container_name: paperless-nextcloud-sync
    restart: unless-stopped
    volumes:
      - '/media/myNextcloudDrive/Scans/Document_Library/documents/archive:/mnt/source:ro'
      - '/media/myNextcloudDrive/nc_data/Scanner/files/Paperless_Archive:/mnt/compare:ro'
      - '/home/docker_admin/paperless-nextcloud-sync/sync.sh:/usr/local/bin/sync.sh'
      #- './ncsync/sync.sh:/usr/local/bin/sync.sh'
      - '/home/docker_admin/paperless-nextcloud-sync/crontabs:/var/spool/cron/crontabs/root'
      #- './ncsync/crontabs:/var/spool/cron/crontabs/root'
    environment:
      WEBDRIVE_URL: $NEXTCLOUD_URL
      WEBDRIVE_USER: $NEXTCLOUD_USER
      WEBDRIVE_PASSWORD: $NEXTCLOUD_PASSWORD
      SYNC_USERID: 33
      SYNC_GROUPID: 33
      SYNC_ACCESS_FILE: 600
      SYNC_ACCESS_DIR: 755
      LC_ALL: de_DE.UTF-8
      LANGUAGE: de_DE.de
      LANG: de_DE.UTF-8
      TZ: Europe/Berlin
    privileged: true
    devices:
      - "/dev/fuse"
    logging:
      options:
        max-size: "10m"
