version: "3"

services:
  nc-sync:
    image: paperless-nextcloud-sync
    restart: unless-stopped
    volumes:
      - '/mnt/data/paperless_data/Document_Library/documents/archive:/mnt/source:ro'
      - '/mnt/data/nextcloud_data/Paperless/files/Paperless_archive:/mnt/compare:ro'
      - './nc-sync/sync.sh:/usr/local/bin/sync.sh:ro'
    environment:
      WEBDRIVE_URL: $NEXTCLOUD_URL
      WEBDRIVE_USER: $NEXTCLOUD_USER
      WEBDRIVE_PASSWORD: $NEXTCLOUD_PASSWORD
      SYNC_USERID: 33
      SYNC_GROUPID: 33
      SYNC_ACCESS_FILE: 600
      SYNC_ACCESS_DIR: 755
      LC_ALL: de_DE.UTF-8
      LANGUAGE: de_DE.de
      LANG: de_DE.UTF-8
      TZ: Europe/Berlin
    privileged: true
    devices:
      - "/dev/fuse"
    logging:
      options:
        max-size: "10m"
