name: Update README on Docker-Hub

on:
  workflow_dispatch:


jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          enable-url-completion: true
